### ISSUE TITLE
rget

### ISSUE THREAD

**Issue by matthieugomez** [xiaodaigh/Fread.jl#1]
Out of curiosity, why do you transfer the data using Feather rather than `@rget`?

**Comment by xiaodaigh** [comment]
It's often faster from memory. Especially for large datasets

**Comment by matthieugomez** [comment]
Yes that's what I remember. Is not that surprising though?

**Comment by xiaodaigh** [comment]
Maybe @rget isn't that efficient? Worth checking out.

**Comment by xiaodaigh** [comment]
Hopefully RCall.jl will have Arrow integration. Hopefully Julia can join the Arrow initiative.
